### ISSUE TITLE
Calling the Pair.getAddress returns inexistant address

### ISSUE THREAD

**Issue by moutikabdessabour** [KingdomStudiosIO/sdk#4]
Currently working on building a connector for defikingdoms to hummingbot. However when I am testing to check if the code works I keep getting an error that basically states that ethers can't find the contract in the address returned by Pair.getAddress 
## MWE:
``` js
const defikingdoms = require('@defikingdoms/sdk');
const { providers } = require('ethers');
let {quoteToken_data, baseToken_data, provider_rpc} = {
    "quoteToken_data": {
        "name": "Jewel",
        "address": "0x72Cb10C6bfA5624dD07Ef608027E366bd690048F",
        "symbol": "JWL",
        "decimals": 18,
        "chainId": 1666700000
    },
    "baseToken_data": {
        "chainId": 1666700000,
        "address": "0x03ff0ff224f904be3118461335064bb48df47938",
        "symbol": "ONE",
        "name": "One",
        "decimals": 18,
      },"provider_rpc":"https://api.s0.t.hmny.io/"};

function getToken(uniswapish, token){
    return new uniswapish.Token(
        token.chainId,
        token.address,
        token.decimals,
        token.symbol,
        token.name
    );
}

(async () => {
    const baseToken  =  getToken(defikingdoms,baseToken_data);
    const quoteToken =  getToken(defikingdoms,quoteToken_data);
    const provider = new providers.StaticJsonRpcProvider(provider_rpc);
    try{
        console.log(defikingdoms.Pair.getAddress(baseToken, quoteToken));
        console.log(await defikingdoms.Fetcher.fetchPairData(
        baseToken,
        quoteToken,
        provider
      ))
    } catch(e){
        console.log(e)
    }
})()
```
Output
```
0x6C595af289691162AA6B6DE46ab627cd9287602f
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getReserves()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.1)
    at Logger.makeError (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Interface.decodeFunctionResult (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/lib/interface.js:389:23)
    at Contract.<anonymous> (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/contracts/lib/index.js:320:56)
    at step (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/sabor/freelancer/leo/testing/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getReserves()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x6C595af289691162AA6B6DE46ab627cd9287602f',
  args: [],
  transaction: {
    data: '0x0902f1ac',
    to: '0x6C595af289691162AA6B6DE46ab627cd9287602f'
  }
}
```
A quick check on the harmony blockchain shows that the address `0x6C595af289691162AA6B6DE46ab627cd9287602f` doesn't exist 

![image](https://user-images.githubusercontent.com/11250014/168069166-f986591f-3a7e-4bd3-bec8-260fc7ba465b.png)

**Comment by moutikabdessabour** [comment]
I was using the wrong token addresses even though those are valid addresses on the Harmony blockchain.
This is an extensive list of the [DefiKingdoms](https://raw.githubusercontent.com/tradescrow/token-lists/main/build/tradescrow-all.tokenlist.json) tokens.
Leaving this for future reference [tokenlist.org](https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/tradescrow/token-lists/main/build/tradescrow-all.tokenlist.json).
